'useclient'

import{useState,useEffect}from'react'
import{useRouter}from'next/navigation'
import{tripApi,vehicleApi,driverApi}from'@/lib/api'

exportdefaultfunctionTripsPage(){
constrouter=useRouter()
const[searchQuery,setSearchQuery]=useState('')
const[statusFilter,setStatusFilter]=useState('all')
const[showAssignModal,setShowAssignModal]=useState(false)
const[showDetailsModal,setShowDetailsModal]=useState(false)
const[showFuelRequestModal,setShowFuelRequestModal]=useState(false)
const[selectedTrip,setSelectedTrip]=useState<any>(null)
const[showToast,setShowToast]=useState(false)
const[toastMessage,setToastMessage]=useState('')
const[toastType,setToastType]=useState<'success'|'error'>('success')
const[assignmentData,setAssignmentData]=useState({
vehicleId:'',
driverId:''
})
const[fuelRequest,setFuelRequest]=useState({
amount:'',
urgency:'normal',
notes:''
})
const[tripsList,setTripsList]=useState<any[]>([])
const[availableVehicles,setAvailableVehicles]=useState<any[]>([])
const[availableDrivers,setAvailableDrivers]=useState<any[]>([])
const[loading,setLoading]=useState(true)

useEffect(()=>{
loadTripsData()
},[])

constloadTripsData=async()=>{
try{
const[trips,vehicles,drivers]=awaitPromise.all([
tripApi.getAllTrips(),
vehicleApi.getAvailableVehicles(),
driverApi.getAvailableDrivers()
])

setTripsList(Array.isArray(trips)?trips:[])
setAvailableVehicles(Array.isArray(vehicles)?vehicles:[])
setAvailableDrivers(Array.isArray(drivers)?drivers:[])
}catch(error:any){
console.error('Failedtoloadtripsdata:',error)
if(error?.message?.includes('token')||error?.message?.includes('Unauthorized')){
router.push('/login')
}
}finally{
setLoading(false)
}
}

//Toastnotificationhandler
constshowNotification=(message:string,type:'success'|'error'='success')=>{
setToastMessage(message)
setToastType(type)
setShowToast(true)
setTimeout(()=>setShowToast(false),3000)
}

//HandleAssignVehicle&Driver
consthandleAssignTrip=(trip:any)=>{
setSelectedTrip(trip)
setAssignmentData({vehicleId:'',driverId:''})
setShowAssignModal(true)
}

//HandleSaveAssignment
consthandleSaveAssignment=async()=>{
if(!assignmentData.vehicleId||!assignmentData.driverId){
showNotification('Pleaseselectbothvehicleanddriver','error')
return
}

try{
awaittripApi.assignVehicleAndDriver(
selectedTrip.id,
assignmentData.vehicleId,
assignmentData.driverId
)

constselectedVehicle=availableVehicles.find((v:any)=>v.id===assignmentData.vehicleId)
constselectedDriver=availableDrivers.find((d:any)=>d.id===assignmentData.driverId)

setTripsList((tripsListasany[]).map((trip:any)=>
trip.id===selectedTrip.id
?{
...trip,
status:'Assigned',
statusColor:'bg-emerald-100text-emerald-700',
vehicle:selectedVehicle?{id:selectedVehicle.id,name:selectedVehicle.model||selectedVehicle.name,plate:selectedVehicle.plateNumber||selectedVehicle.plate,fuelLevel:selectedVehicle.fuelLevel||100}:null,
driver:selectedDriver?{id:selectedDriver.id,name:selectedDriver.name,phone:selectedDriver.phone}:null
}
:trip
))

setShowAssignModal(false)
setSelectedTrip(null)
setAssignmentData({vehicleId:'',driverId:''})
showNotification(`Vehicleanddriverassignedsuccessfullyto${selectedTrip.id}!`)
}catch(error:any){
showNotification(error?.message||'Failedtoassignvehicleanddriver','error')
}
}

//HandleViewDetails
consthandleViewDetails=(trip:any)=>{
setSelectedTrip(trip)
setShowDetailsModal(true)
}

//HandleRequestFuel
consthandleRequestFuel=(trip:any)=>{
setSelectedTrip(trip)
setFuelRequest({amount:'',urgency:'normal',notes:''})
setShowFuelRequestModal(true)
}

//HandleSubmitFuelRequest
consthandleSubmitFuelRequest=()=>{
if(!fuelRequest.amount){
showNotification('Pleaseenterfuelamount','error')
return
}

//Closemodalfirst
setShowFuelRequestModal(false)
setSelectedTrip(null)
setFuelRequest({amount:'',urgency:'normal',notes:''})

//Inarealapp,thiswouldsendtherequesttotheadmin
showNotification(`Fuelrequestsubmittedsuccessfully(${fuelRequest.amount}L)!`)
}

constgetFilteredTrips=()=>{
returntripsList.filter(trip=>{
constmatchesSearch=searchQuery===''||
trip.id.toLowerCase().includes(searchQuery.toLowerCase())||
trip.requestedBy.toLowerCase().includes(searchQuery.toLowerCase())||
trip.department.toLowerCase().includes(searchQuery.toLowerCase())||
trip.destination.toLowerCase().includes(searchQuery.toLowerCase())

constmatchesStatus=statusFilter==='all'||
trip.status.toLowerCase().replace('','-')===statusFilter.toLowerCase()

returnmatchesSearch&&matchesStatus
})
}

constfilteredTrips=getFilteredTrips()

return(
<divclassName="p-4sm:p-6lg:p-8">
{/*ToastNotification*/}
{showToast&&(
<divclassName="fixedtop-4right-4z-50animate-fade-in">
<divclassName={`px-6py-3rounded-lgshadow-lg${toastType==='success'?'bg-emerald-600':'bg-red-600'}text-white`}>
{toastMessage}
</div>
</div>
)}

{/*PageHeader*/}
<divclassName="mb-6">
<h1className="text-2xlmd:text-3xlfont-boldtext-gray-800">TripManagement</h1>
<pclassName="text-smtext-gray-600mt-1">Manageapprovedtripsandassignvehicles&drivers</p>
</div>

{/*Filters*/}
<divclassName="bg-whiterounded-xlp-4sm:p-6borderborder-gray-200mb-6">
<divclassName="flexflex-colsm:flex-rowitems-stretchsm:items-centergap-3sm:gap-4">
<divclassName="flex-1">
<divclassName="relative">
<input
type="text"
placeholder="SearchbyID,requester,department,ordestination..."
value={searchQuery}
onChange={(e)=>setSearchQuery(e.target.value)}
className="w-fullpl-10pr-4py-2text-smborderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500focus:border-transparentoutline-none"
/>
<svgclassName="w-5h-5text-gray-400absoluteleft-3top-1/2-translate-y-1/2"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M2121l-6-6m2-5a77011-14077001140z"/>
</svg>
</div>
</div>

<select
value={statusFilter}
onChange={(e)=>setStatusFilter(e.target.value)}
className="px-4py-2text-smborderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500focus:border-transparentoutline-none"
>
<optionvalue="all">AllStatus</option>
<optionvalue="pending-assignment">PendingAssignment</option>
<optionvalue="assigned">Assigned</option>
<optionvalue="in-progress">InProgress</option>
<optionvalue="completed">Completed</option>
</select>
</div>
</div>

{/*TripsList*/}
<divclassName="space-y-4">
{filteredTrips.map((trip)=>(
<divkey={trip.id}className="bg-whiterounded-xlborderborder-gray-200p-4md:p-6hover:shadow-lgtransition-shadow">
<divclassName="flexflex-collg:flex-rowlg:items-centergap-4">
{/*TripInfo*/}
<divclassName="flex-1">
<divclassName="flexitems-startjustify-betweenmb-3">
<div>
<h3className="text-lgfont-boldtext-gray-900">{trip.id}</h3>
<pclassName="text-smtext-gray-600">{trip.requestedBy}•{trip.department}</p>
</div>
<spanclassName={`px-3py-1rounded-fulltext-xsfont-medium${trip.statusColor}`}>
{trip.status}
</span>
</div>

<divclassName="gridgrid-cols-1md:grid-cols-2gap-3mb-3">
<divclassName="flexitems-centergap-2text-sm">
<svgclassName="w-4h-4text-gray-400"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M17.65716.657L13.41420.9a1.9981.998001-2.8270l-4.244-4.243a8801111.3140z"/>
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M1511a33011-603300160z"/>
</svg>
<spanclassName="text-gray-700"><spanclassName="font-medium">Destination:</span>{trip.destination}</span>
</div>
<divclassName="flexitems-centergap-2text-sm">
<svgclassName="w-4h-4text-gray-400"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M87V3m84V3m-98h10M521h14a220002-2V7a22000-2-2H5a22000-22v12a2200022z"/>
</svg>
<spanclassName="text-gray-700"><spanclassName="font-medium">Date:</span>{trip.startDate}to{trip.endDate}</span>
</div>
<divclassName="flexitems-centergap-2text-sm">
<svgclassName="w-4h-4text-gray-400"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M128v4l33m6-3a99011-18099001180z"/>
</svg>
<spanclassName="text-gray-700"><spanclassName="font-medium">Duration:</span>{trip.duration}</span>
</div>
<divclassName="flexitems-centergap-2text-sm">
<svgclassName="w-4h-4text-gray-400"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M1720h5v-2a33000-5.356-1.857M1720H7m100v-2c0-.656-.126-1.283-.356-1.857M720H2v-2a330015.356-1.857M720v-2c0-.656.126-1.283.356-1.857m00a5.0025.0020019.2880M157a33011-603300160zm63a22011-402200140zM710a22011-402200140z"/>
</svg>
<spanclassName="text-gray-700"><spanclassName="font-medium">Passengers:</span>{trip.passengers}</span>
</div>
</div>

<divclassName="text-smtext-gray-700">
<spanclassName="font-medium">Purpose:</span>{trip.purpose}
</div>

{/*AssignmentInfo*/}
{trip.vehicle&&trip.driver&&(
<divclassName="mt-4pt-4border-tborder-gray-200">
<divclassName="gridgrid-cols-1md:grid-cols-2gap-3">
<divclassName="bg-emerald-50rounded-lgp-3">
<divclassName="flexitems-centergap-2mb-2">
<svgclassName="w-4h-4text-emerald-600"fill="currentColor"viewBox="002020">
<pathd="M816.5a1.51.5011-301.51.500130zM1516.5a1.51.5011-301.51.500130z"/>
<pathd="M34a11000-11v10a1100011h1.05a2.52.50014.90H10a110001-1V5a11000-1-1H3zM147a11000-11v6.05A2.52.500115.9516H17a110001-1v-5a11000-.293-.707l-2-2A11000157h-1z"/>
</svg>
<spanclassName="text-xsfont-semiboldtext-emerald-700">AssignedVehicle</span>
</div>
<pclassName="text-smfont-mediumtext-gray-900">{trip.vehicle.name}</p>
<pclassName="text-xstext-gray-600">{trip.vehicle.plate}</p>

{/*FuelLevel*/}
<divclassName="mt-2">
<divclassName="flexitems-centerjustify-betweenmb-1">
<spanclassName="text-xstext-gray-600">FuelLevel</span>
<spanclassName={`text-xsfont-medium${
trip.vehicle.fuelLevel>=70?'text-emerald-600':
trip.vehicle.fuelLevel>=40?'text-yellow-600':
'text-red-600'
}`}>
{trip.vehicle.fuelLevel}%
</span>
</div>
<divclassName="w-fullbg-gray-200rounded-fullh-2">
<div
className={`h-2rounded-fulltransition-all${
trip.vehicle.fuelLevel>=70?'bg-emerald-500':
trip.vehicle.fuelLevel>=40?'bg-yellow-500':
'bg-red-500'
}`}
style={{width:`${trip.vehicle.fuelLevel}%`}}
></div>
</div>
</div>
</div>
<divclassName="bg-blue-50rounded-lgp-3">
<divclassName="flexitems-centergap-2mb-2">
<svgclassName="w-4h-4text-blue-600"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M167a44011-804400180zM1214a77000-77h14a77000-7-7z"/>
</svg>
<spanclassName="text-xsfont-semiboldtext-blue-700">AssignedDriver</span>
</div>
<pclassName="text-smfont-mediumtext-gray-900">{trip.driver.name}</p>
<pclassName="text-xstext-gray-600">{trip.driver.phone}</p>
</div>
</div>
</div>
)}
</div>

{/*Actions*/}
<divclassName="flexlg:flex-colgap-2">
<button
onClick={()=>handleViewDetails(trip)}
className="flex-1lg:flex-nonepx-4py-2bg-gray-100text-gray-700rounded-lgtext-smfont-mediumhover:bg-gray-200transition-colors"
>
ViewDetails
</button>
{trip.status==='PendingAssignment'&&(
<button
onClick={()=>handleAssignTrip(trip)}
className="flex-1lg:flex-nonepx-4py-2bg-emerald-500text-whiterounded-lgtext-smfont-mediumhover:bg-emerald-600transition-colors"
>
AssignVehicle
</button>
)}
{trip.vehicle&&trip.vehicle.fuelLevel<70&&(
<button
onClick={()=>handleRequestFuel(trip)}
className="flex-1lg:flex-nonepx-4py-2bg-orange-500text-whiterounded-lgtext-smfont-mediumhover:bg-orange-600transition-colorsflexitems-centerjustify-centergap-1"
>
<svgclassName="w-4h-4"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M126v6m00v6m0-6h6m-60H6"/>
</svg>
RequestFuel
</button>
)}
</div>
</div>
</div>
))}
</div>

{/*NoResults*/}
{filteredTrips.length===0&&(
<divclassName="bg-whiterounded-xlp-12text-centerborderborder-gray-200">
<svgclassName="w-16h-16text-gray-300mx-automb-4"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M95H7a22000-22v12a2200022h10a220002-2V7a22000-2-2h-2M95a2200022h2a220002-2M95a220012-2h2a2200122"/>
</svg>
<h3className="text-lgfont-mediumtext-gray-900mb-2">Notripsfound</h3>
<pclassName="text-gray-500">Tryadjustingyoursearchorfiltercriteria</p>
</div>
)}

{/*AssignVehicle&DriverModal*/}
{showAssignModal&&selectedTrip&&(
<divclassName="fixedinset-0bg-blackbg-opacity-50backdrop-blur-smflexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-2xlshadow-2xlmax-w-2xlw-fullp-6max-h-[90vh]overflow-y-auto">
<divclassName="flexitems-centerjustify-betweenmb-6">
<h3className="text-xlfont-boldtext-gray-800">AssignVehicle&Driver</h3>
<button
onClick={()=>setShowAssignModal(false)}
className="p-2hover:bg-gray-100rounded-lg"
>
<svgclassName="w-5h-5"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M618L186M66l1212"/>
</svg>
</button>
</div>

{/*TripSummary*/}
<divclassName="bg-gray-50rounded-lgp-4mb-6">
<h4className="font-semiboldtext-gray-800mb-3">TripInformation</h4>
<divclassName="gridgrid-cols-2gap-3text-sm">
<div>
<spanclassName="text-gray-600">TripID:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.id}</p>
</div>
<div>
<spanclassName="text-gray-600">Requester:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.requestedBy}</p>
</div>
<div>
<spanclassName="text-gray-600">Destination:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.destination}</p>
</div>
<div>
<spanclassName="text-gray-600">Passengers:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.passengers}people</p>
</div>
<div>
<spanclassName="text-gray-600">Duration:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.duration}</p>
</div>
<div>
<spanclassName="text-gray-600">StartDate:</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.startDate}</p>
</div>
</div>
</div>

{/*VehicleSelection*/}
<divclassName="mb-6">
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-3">SelectVehicle</label>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-3">
{availableVehicles.map((vehicle)=>(
<div
key={vehicle.id}
onClick={()=>setAssignmentData({...assignmentData,vehicleId:vehicle.id})}
className={`p-4border-2rounded-lgcursor-pointertransition-all${
assignmentData.vehicleId===vehicle.id
?'border-emerald-500bg-emerald-50'
:'border-gray-200hover:border-emerald-300'
}`}
>
<divclassName="flexitems-startgap-3">
<divclassName={`w-10h-10rounded-lgflexitems-centerjustify-center${
assignmentData.vehicleId===vehicle.id?'bg-emerald-500':'bg-gray-100'
}`}>
<svgclassName={`w-6h-6${assignmentData.vehicleId===vehicle.id?'text-white':'text-gray-600'}`}fill="currentColor"viewBox="002020">
<pathd="M816.5a1.51.5011-301.51.500130zM1516.5a1.51.5011-301.51.500130z"/>
<pathd="M34a11000-11v10a1100011h1.05a2.52.50014.90H10a110001-1V5a11000-1-1H3zM147a11000-11v6.05A2.52.500115.9516H17a110001-1v-5a11000-.293-.707l-2-2A11000157h-1z"/>
</svg>
</div>
<divclassName="flex-1">
<pclassName="font-mediumtext-gray-900">{vehicle.name}</p>
<pclassName="text-xstext-gray-600">{vehicle.plate}</p>
<divclassName="flexitems-centergap-2mt-1">
<spanclassName="text-xspx-2py-0.5bg-gray-100text-gray-700rounded">{vehicle.type}</span>
<spanclassName="text-xstext-gray-600">{vehicle.capacity}</span>
</div>
</div>
</div>
</div>
))}
</div>
</div>

{/*DriverSelection*/}
<divclassName="mb-6">
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-3">SelectDriver</label>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-3">
{availableDrivers.map((driver)=>(
<div
key={driver.id}
onClick={()=>setAssignmentData({...assignmentData,driverId:driver.id})}
className={`p-4border-2rounded-lgcursor-pointertransition-all${
assignmentData.driverId===driver.id
?'border-blue-500bg-blue-50'
:'border-gray-200hover:border-blue-300'
}`}
>
<divclassName="flexitems-startgap-3">
<divclassName={`w-10h-10rounded-lgflexitems-centerjustify-center${
assignmentData.driverId===driver.id?'bg-blue-500':'bg-gray-100'
}`}>
<svgclassName={`w-6h-6${assignmentData.driverId===driver.id?'text-white':'text-gray-600'}`}fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M167a44011-804400180zM1214a77000-77h14a77000-7-7z"/>
</svg>
</div>
<divclassName="flex-1">
<pclassName="font-mediumtext-gray-900">{driver.name}</p>
<pclassName="text-xstext-gray-600">{driver.phone}</p>
<divclassName="flexitems-centergap-2mt-1">
<spanclassName="text-xspx-2py-0.5bg-gray-100text-gray-700rounded">{driver.license}</span>
<spanclassName="text-xstext-gray-600">{driver.experience}</span>
</div>
</div>
</div>
</div>
))}
</div>
</div>

<divclassName="flexgap-3">
<button
onClick={()=>setShowAssignModal(false)}
className="flex-1px-4py-2borderborder-gray-300rounded-lghover:bg-gray-50transition-colors"
>
Cancel
</button>
<button
onClick={handleSaveAssignment}
className="flex-1px-4py-2bg-emerald-600text-whiterounded-lghover:bg-emerald-700transition-colors"
>
Assign
</button>
</div>
</div>
</div>
)}

{/*TripDetailsModal*/}
{showDetailsModal&&selectedTrip&&(
<divclassName="fixedinset-0bg-blackbg-opacity-50backdrop-blur-smflexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-2xlshadow-2xlmax-w-3xlw-fullp-6max-h-[90vh]overflow-y-auto">
<divclassName="flexitems-centerjustify-betweenmb-6">
<h3className="text-xlfont-boldtext-gray-800">TripDetails</h3>
<button
onClick={()=>setShowDetailsModal(false)}
className="p-2hover:bg-gray-100rounded-lg"
>
<svgclassName="w-5h-5"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M618L186M66l1212"/>
</svg>
</button>
</div>

{/*TripInformation*/}
<divclassName="mb-6">
<divclassName="flexitems-centerjustify-betweenmb-4">
<h4className="font-semiboldtext-gray-800">TripInformation</h4>
<spanclassName={`px-3py-1rounded-fulltext-xsfont-medium${selectedTrip.statusColor}`}>
{selectedTrip.status}
</span>
</div>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-4">
<div>
<spanclassName="text-smtext-gray-600">TripID</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.id}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">RequestedBy</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.requestedBy}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">Department</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.department}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">Destination</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.destination}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">StartDate</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.startDate}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">EndDate</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.endDate}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">Duration</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.duration}</p>
</div>
<div>
<spanclassName="text-smtext-gray-600">Passengers</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.passengers}people</p>
</div>
<divclassName="md:col-span-2">
<spanclassName="text-smtext-gray-600">Purpose</span>
<pclassName="font-mediumtext-gray-900">{selectedTrip.purpose}</p>
</div>
</div>
</div>

{/*ApprovalChain*/}
<divclassName="mb-6">
<h4className="font-semiboldtext-gray-800mb-4">ApprovalChain</h4>
<divclassName="space-y-3">
{selectedTrip.approvals.map((approval:any,index:number)=>(
<divkey={index}className="flexitems-centergap-4p-3bg-emerald-50rounded-lg">
<divclassName="w-10h-10bg-emerald-500rounded-fullflexitems-centerjustify-centerflex-shrink-0">
<svgclassName="w-6h-6text-white"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M513l44L197"/>
</svg>
</div>
<divclassName="flex-1">
<pclassName="font-mediumtext-gray-900">{approval.role}</p>
<pclassName="text-smtext-gray-600">{approval.approver}</p>
</div>
<divclassName="text-right">
<spanclassName="text-xspx-2py-1bg-emerald-100text-emerald-700roundedfont-medium">
{approval.status}
</span>
<pclassName="text-xstext-gray-500mt-1">{approval.date}</p>
</div>
</div>
))}
</div>
</div>

{/*AssignmentDetails*/}
{selectedTrip.vehicle&&selectedTrip.driver&&(
<divclassName="mb-6">
<h4className="font-semiboldtext-gray-800mb-4">AssignmentDetails</h4>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-4">
<divclassName="bg-emerald-50rounded-lgp-4">
<divclassName="flexitems-centergap-2mb-3">
<svgclassName="w-5h-5text-emerald-600"fill="currentColor"viewBox="002020">
<pathd="M816.5a1.51.5011-301.51.500130zM1516.5a1.51.5011-301.51.500130z"/>
<pathd="M34a11000-11v10a1100011h1.05a2.52.50014.90H10a110001-1V5a11000-1-1H3zM147a11000-11v6.05A2.52.500115.9516H17a110001-1v-5a11000-.293-.707l-2-2A11000157h-1z"/>
</svg>
<spanclassName="font-semiboldtext-emerald-700">AssignedVehicle</span>
</div>
<pclassName="font-mediumtext-gray-900">{selectedTrip.vehicle.name}</p>
<pclassName="text-smtext-gray-600">{selectedTrip.vehicle.plate}</p>
</div>
<divclassName="bg-blue-50rounded-lgp-4">
<divclassName="flexitems-centergap-2mb-3">
<svgclassName="w-5h-5text-blue-600"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M167a44011-804400180zM1214a77000-77h14a77000-7-7z"/>
</svg>
<spanclassName="font-semiboldtext-blue-700">AssignedDriver</span>
</div>
<pclassName="font-mediumtext-gray-900">{selectedTrip.driver.name}</p>
<pclassName="text-smtext-gray-600">{selectedTrip.driver.phone}</p>
</div>
</div>
</div>
)}

<divclassName="flexgap-3">
<button
onClick={()=>setShowDetailsModal(false)}
className="flex-1px-4py-2borderborder-gray-300rounded-lghover:bg-gray-50transition-colors"
>
Close
</button>
</div>
</div>
</div>
)}

{/*FuelRequestModal*/}
{showFuelRequestModal&&selectedTrip&&selectedTrip.vehicle&&(
<divclassName="fixedinset-0bg-blackbg-opacity-50backdrop-blur-smflexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-2xlshadow-2xlmax-w-mdw-fullp-6">
<divclassName="flexitems-centerjustify-betweenmb-6">
<h3className="text-xlfont-boldtext-gray-800">RequestFuel</h3>
<button
onClick={()=>setShowFuelRequestModal(false)}
className="p-2hover:bg-gray-100rounded-lg"
>
<svgclassName="w-5h-5"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M618L186M66l1212"/>
</svg>
</button>
</div>

{/*VehicleInfo*/}
<divclassName="bg-gray-50rounded-lgp-4mb-6">
<h4className="font-semiboldtext-gray-800mb-3">VehicleInformation</h4>
<divclassName="space-y-2text-sm">
<divclassName="flexjustify-between">
<spanclassName="text-gray-600">Vehicle:</span>
<spanclassName="font-mediumtext-gray-900">{selectedTrip.vehicle.name}</span>
</div>
<divclassName="flexjustify-between">
<spanclassName="text-gray-600">Plate:</span>
<spanclassName="font-mediumtext-gray-900">{selectedTrip.vehicle.plate}</span>
</div>
<divclassName="flexjustify-between">
<spanclassName="text-gray-600">TripID:</span>
<spanclassName="font-mediumtext-gray-900">{selectedTrip.id}</span>
</div>
<divclassName="flexjustify-betweenitems-center">
<spanclassName="text-gray-600">CurrentFuel:</span>
<divclassName="flexitems-centergap-2">
<divclassName="w-20bg-gray-200rounded-fullh-2">
<div
className={`h-2rounded-full${
selectedTrip.vehicle.fuelLevel>=70?'bg-emerald-500':
selectedTrip.vehicle.fuelLevel>=40?'bg-yellow-500':
'bg-red-500'
}`}
style={{width:`${selectedTrip.vehicle.fuelLevel}%`}}
></div>
</div>
<spanclassName={`font-medium${
selectedTrip.vehicle.fuelLevel>=70?'text-emerald-600':
selectedTrip.vehicle.fuelLevel>=40?'text-yellow-600':
'text-red-600'
}`}>
{selectedTrip.vehicle.fuelLevel}%
</span>
</div>
</div>
</div>
</div>

{/*FuelRequestForm*/}
<divclassName="space-y-4">
<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-1">FuelAmount(Liters)*</label>
<input
type="number"
value={fuelRequest.amount}
onChange={(e)=>setFuelRequest({...fuelRequest,amount:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500focus:border-transparentoutline-none"
placeholder="e.g.,50"
min="1"
/>
</div>

<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-1">UrgencyLevel*</label>
<select
value={fuelRequest.urgency}
onChange={(e)=>setFuelRequest({...fuelRequest,urgency:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500focus:border-transparentoutline-none"
>
<optionvalue="low">Low-Canwait</option>
<optionvalue="normal">Normal-Within24hours</option>
<optionvalue="high">High-Urgent(within6hours)</option>
<optionvalue="critical">Critical-Immediate</option>
</select>
</div>

<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-1">AdditionalNotes</label>
<textarea
value={fuelRequest.notes}
onChange={(e)=>setFuelRequest({...fuelRequest,notes:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500focus:border-transparentoutline-none"
placeholder="Anyadditionalinformation..."
rows={3}
/>
</div>
</div>

<divclassName="flexgap-3mt-6">
<button
onClick={()=>setShowFuelRequestModal(false)}
className="flex-1px-4py-2borderborder-gray-300rounded-lghover:bg-gray-50transition-colors"
>
Cancel
</button>
<button
onClick={handleSubmitFuelRequest}
className="flex-1px-4py-2bg-orange-600text-whiterounded-lghover:bg-orange-700transition-colors"
>
SubmitRequest
</button>
</div>
</div>
</div>
)}
</div>
)
}



