'useclient'

import{useState,useEffect}from'react'
import{useRouter}from'next/navigation'
import{tripApi,vehicleApi,driverApi,maintenanceApi}from'@/lib/api'

exportdefaultfunctionDashboardPage(){
constrouter=useRouter()
const[selectedPeriod,setSelectedPeriod]=useState('week')
const[showToast,setShowToast]=useState(false)
const[toastMessage,setToastMessage]=useState('')
const[toastType,setToastType]=useState<'success'|'error'>('success')
const[approvedRequests,setApprovedRequests]=useState<any[]>([])
const[allTrips,setAllTrips]=useState<any[]>([])
const[availableVehicles,setAvailableVehicles]=useState<any[]>([])
const[availableDrivers,setAvailableDrivers]=useState<any[]>([])
const[pendingMaintenance,setPendingMaintenance]=useState<any[]>([])
const[vehicleStats,setVehicleStats]=useState({total:0,available:0,inUse:0,maintenance:0})
const[loading,setLoading]=useState(true)
const[selectedRequest,setSelectedRequest]=useState<any>(null)
const[showAssignModal,setShowAssignModal]=useState(false)
const[assignmentData,setAssignmentData]=useState({vehicleId:'',driverId:'',estimatedFuelCost:'',estimatedDistance:''})

useEffect(()=>{loadDashboardData()},[])

constloadDashboardData=async()=>{
try{
const[approvedTrips,allVehicles,assignableVehicles,drivers,maintenance,allTripsData]=awaitPromise.all([
tripApi.getApprovedTrips().catch(()=>[]),
vehicleApi.getAllVehicles().catch(()=>[]),
vehicleApi.getAvailableVehicles().catch(()=>[]),
driverApi.getAvailableDrivers().catch(()=>[]),
maintenanceApi.getAllMaintenanceRequests().catch(()=>[]),
tripApi.getAllTrips().catch(()=>[]),
])
constvehicles=Array.isArray(allVehicles)?allVehicles:[]
constforAssignment=Array.isArray(assignableVehicles)?assignableVehicles:[]
constassignableIds=newSet(forAssignment.map((v:any)=>v.id))
consttrips=Array.isArray(approvedTrips)?approvedTrips:[]
constmaint=Array.isArray(maintenance)?maintenance:[]
setApprovedRequests(trips)
setAllTrips(Array.isArray(allTripsData)?allTripsData:[])
setAvailableVehicles(forAssignment)
setAvailableDrivers(Array.isArray(drivers)?drivers:[])
setPendingMaintenance(maint.filter((m:any)=>['Submitted','UnderInspection'].includes(m.status)).slice(0,5))
constactiveFleet=vehicles.filter((v:any)=>v.status==='Active')
constinUseActive=activeFleet.filter((v:any)=>!assignableIds.has(v.id)).length
setVehicleStats({
total:vehicles.length,
available:forAssignment.length,
inUse:inUseActive,
maintenance:vehicles.filter((v:any)=>v.status==='UnderMaintenance'||v.status==='Maintenance').length,
})
}catch(err){
console.error(err)
}finally{
setLoading(false)
}
}

constshowNotification=(msg:string,type:'success'|'error'='success')=>{
setToastMessage(msg);setToastType(type);setShowToast(true)
setTimeout(()=>setShowToast(false),3000)
}

consthandleAssign=async()=>{
if(!assignmentData.vehicleId||!assignmentData.driverId){
showNotification('Pleaseselectbothvehicleanddriver','error');return
}
try{
awaittripApi.assignVehicleAndDriver(
selectedRequest.id,
assignmentData.vehicleId,
assignmentData.driverId,
Number(assignmentData.estimatedFuelCost)||0,
Number(assignmentData.estimatedDistance)||0,
)
setApprovedRequests(prev=>prev.filter((r:any)=>r.id!==selectedRequest.id))
setShowAssignModal(false);setSelectedRequest(null)
setAssignmentData({vehicleId:'',driverId:'',estimatedFuelCost:'',estimatedDistance:''})
showNotification('Vehicleanddriverassignedsuccessfully!')
}catch(err:any){
showNotification(err?.message||'Failedtoassign','error')
}
}

//Weeklytripcountsbyday
constdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
constdayCounts=[1,2,3,4,5,6,0].map(d=>approvedRequests.filter((t:any)=>newDate(t.createdAt).getDay()===d).length)
constmaxDay=Math.max(...dayCounts,1)

//Donut
constcirc=2*Math.PI*40
consttotal=Math.max(vehicleStats.total,1)
constavailDash=(vehicleStats.available/total)*circ
constinUseDash=(vehicleStats.inUse/total)*circ
constmaintDash=(vehicleStats.maintenance/total)*circ

conststateLabel:Record<string,{label:string;color:string}>={
APPROVED_FOR_ALLOCATION:{label:'APPROVED',color:'bg-emerald-100text-emerald-700'},
CAR_ALLOCATED:{label:'ALLOCATED',color:'bg-blue-100text-blue-700'},
PENDING_TRANSPORT_CONFIRM:{label:'CONFIRMING',color:'bg-yellow-100text-yellow-700'},
READY:{label:'READY',color:'bg-indigo-100text-indigo-700'},
IN_PROGRESS:{label:'ONROUTE',color:'bg-emerald-100text-emerald-700'},
}
constgradients=['from-cyan-400to-blue-500','from-teal-400to-cyan-500','from-blue-400to-indigo-500','from-purple-400to-pink-500']

if(loading)return(
<divclassName="flexitems-centerjustify-centerh-screen">
<divclassName="animate-spinrounded-fullh-16w-16border-b-4border-emerald-600"></div>
</div>
)

return(
<divclassName="p-4md:p-6space-y-6">
{showToast&&(
<divclassName="fixedtop-4right-4z-50">
<divclassName={`px-6py-3rounded-lgshadow-lgtext-white${toastType==='success'?'bg-emerald-600':'bg-red-600'}`}>{toastMessage}</div>
</div>
)}

{/*Header*/}
<divclassName="flexflex-colsm:flex-rowsm:items-centersm:justify-betweengap-3">
<div>
<h1className="text-2xlfont-boldtext-gray-800">FleetOverview</h1>
<pclassName="text-smtext-gray-500mt-1">Real-timefleetmonitoringanddeploymentmanagement</p>
</div>
<divclassName="flexgap-2">
{['day','week','month','year'].map(p=>(
<buttonkey={p}onClick={()=>setSelectedPeriod(p)}
className={`px-3py-2rounded-lgtext-xsfont-mediumtransition-colorscapitalize${selectedPeriod===p?'bg-emerald-500text-white':'bg-whitetext-gray-600hover:bg-gray-100'}`}>
{p}
</button>
))}
</div>
</div>

{/*StatsCards*/}
<divclassName="gridgrid-cols-2lg:grid-cols-4gap-4">
{[
{label:'TotalFleet',value:vehicleStats.total,icon:'M816.5a1.51.5011-301.51.500130zM1516.5a1.51.5011-301.51.500130z',bg:'bg-emerald-100',color:'text-emerald-600'},
{label:'Available',value:vehicleStats.available,icon:'M912l224-4m62a99011-18099001180z',bg:'bg-blue-100',color:'text-blue-600'},
{label:'InUse',value:vehicleStats.inUse,icon:'M1310V3L414h7v7l9-11h-7z',bg:'bg-purple-100',color:'text-purple-600'},
{label:'Maintenance',value:vehicleStats.maintenance,icon:'M10.3254.317c.426-1.7562.924-1.7563.350a1.7241.7240002.5731.066c1.543-.943.31.8262.372.37a1.7241.7240001.0652.572c1.756.4261.7562.92403.35a1.7241.724000-1.0662.573c.941.543-.8263.31-2.372.37a1.7241.724000-2.5721.065c-.4261.756-2.9241.756-3.350a1.7241.724000-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.7241.724000-1.065-2.572c-1.756-.426-1.756-2.9240-3.35a1.7241.7240001.066-2.573c-.94-1.543.826-3.312.37-2.37.996.6082.296.072.572-1.065z',bg:'bg-orange-100',color:'text-orange-600'},
].map(s=>(
<divkey={s.label}className="bg-whiterounded-xlp-5borderborder-gray-200hover:shadow-lgtransition-shadow">
<divclassName="flexitems-centerjustify-betweenmb-3">
<spanclassName="text-smtext-gray-600">{s.label}</span>
<divclassName={`w-10h-10${s.bg}rounded-lgflexitems-centerjustify-center`}>
<svgclassName={`w-5h-5${s.color}`}fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d={s.icon}/>
</svg>
</div>
</div>
<pclassName="text-3xlfont-boldtext-gray-900">{s.value}</p>
</div>
))}
</div>

{/*ChartsRow*/}
<divclassName="gridgrid-cols-1lg:grid-cols-2gap-6">
{/*FleetUtilization*/}
<divclassName="bg-whiterounded-xlp-6borderborder-gray-200">
<h2className="text-basefont-boldtext-gray-900mb-4">TripRequestsbyDay</h2>
<divclassName="space-y-3">
{days.map((day,idx)=>{
constpct=Math.round((dayCounts[idx]/maxDay)*100)
return(
<divkey={day}className="flexitems-centergap-3">
<spanclassName="text-xsfont-mediumtext-gray-600w-10">{day}</span>
<divclassName="flex-1bg-gray-100rounded-fullh-7overflow-hidden">
<divclassName="bg-emerald-500h-fullrounded-fullflexitems-centerjustify-endpr-2transition-allduration-500"
style={{width:`${pct}%`,minWidth:dayCounts[idx]>0?'20px':'0'}}>
{dayCounts[idx]>0&&<spanclassName="text-xsfont-mediumtext-white">{dayCounts[idx]}</span>}
</div>
</div>
</div>
)
})}
</div>
</div>

{/*VehicleStatusDonut*/}
<divclassName="bg-whiterounded-xlp-6borderborder-gray-200">
<h2className="text-basefont-boldtext-gray-900mb-4">VehicleStatus</h2>
<divclassName="flexitems-centergap-6">
<divclassName="relativew-40h-40flex-shrink-0">
<svgclassName="w-fullh-fulltransform-rotate-90"viewBox="00100100">
<circlecx="50"cy="50"r="40"fill="none"stroke="#f3f4f6"strokeWidth="20"/>
<circlecx="50"cy="50"r="40"fill="none"stroke="#10b981"strokeWidth="20"
strokeDasharray={`${availDash}${circ-availDash}`}strokeDashoffset="0"/>
<circlecx="50"cy="50"r="40"fill="none"stroke="#3b82f6"strokeWidth="20"
strokeDasharray={`${inUseDash}${circ-inUseDash}`}strokeDashoffset={-availDash}/>
<circlecx="50"cy="50"r="40"fill="none"stroke="#f97316"strokeWidth="20"
strokeDasharray={`${maintDash}${circ-maintDash}`}strokeDashoffset={-(availDash+inUseDash)}/>
</svg>
<divclassName="absoluteinset-0flexitems-centerjustify-center">
<divclassName="text-center">
<pclassName="text-2xlfont-boldtext-gray-900">{vehicleStats.total}</p>
<pclassName="text-xstext-gray-500">Total</p>
</div>
</div>
</div>
<divclassName="space-y-3flex-1">
{[
{label:'Available',count:vehicleStats.available,color:'bg-emerald-500'},
{label:'InUse',count:vehicleStats.inUse,color:'bg-blue-500'},
{label:'Maintenance',count:vehicleStats.maintenance,color:'bg-orange-500'},
].map(s=>(
<divkey={s.label}className="flexitems-centerjustify-betweentext-sm">
<divclassName="flexitems-centergap-2">
<divclassName={`w-3h-3rounded-full${s.color}`}></div>
<spanclassName="text-gray-600">{s.label}</span>
</div>
<spanclassName="font-boldtext-gray-900">{s.count}({vehicleStats.total>0?Math.round(s.count/vehicleStats.total*100):0}%)</span>
</div>
))}
</div>
</div>
</div>
</div>

{/*MonthlyTripTrend*/}
<divclassName="bg-whiterounded-xlp-6borderborder-gray-200">
<divclassName="flexitems-centerjustify-betweenmb-4">
<div>
<h2className="text-basefont-boldtext-gray-900">MonthlyTripRequests</h2>
<pclassName="text-xstext-gray-500">Last6months—realdata</p>
</div>
</div>
{(()=>{
constnow=newDate()
constmonthly=Array.from({length:6},(_,i)=>{
constd=newDate(now.getFullYear(),now.getMonth()-5+i,1)
constcount=allTrips.filter((t:any)=>{
consttd=newDate(t.createdAt)
returntd.getFullYear()===d.getFullYear()&&td.getMonth()===d.getMonth()
}).length
return{label:d.toLocaleString('default',{month:'short'}),count}
})
constmaxVal=Math.max(...monthly.map(m=>m.count),1)
return(
<div>
<divclassName="flexitems-endgap-2h-32border-bborder-gray-100pb-2">
{monthly.map((m,i)=>(
<divkey={i}className="flex-1flexflex-colitems-centergap-1group">
<divclassName="relativew-full">
<divclassName="absolute-top-6left-1/2-translate-x-1/2bg-gray-800text-whitetext-xspx-1.5py-0.5roundedopacity-0group-hover:opacity-100transition-opacitywhitespace-nowrap">
{m.count}trips
</div>
<divclassName="w-fullbg-gradient-to-tfrom-emerald-600to-emerald-400rounded-thover:from-emerald-700hover:to-emerald-500transition-colors"
style={{height:`${(m.count/maxVal)*120}px`,minHeight:m.count>0?'4px':'0'}}></div>
</div>
<spanclassName="text-xstext-gray-400">{m.label}</span>
</div>
))}
</div>
<divclassName="flexitems-centergap-2mt-3text-xstext-gray-500">
<divclassName="w-3h-3bg-emerald-500rounded"></div>
<span>Total:{allTrips.length}trips</span>
</div>
</div>
)
})()}
</div>

{/*MainGrid*/}
<divclassName="gridgrid-cols-1lg:grid-cols-3gap-6">
{/*ActiveTrips*/}
<divclassName="lg:col-span-2bg-whiterounded-xlp-6borderborder-gray-200">
<divclassName="flexitems-centerjustify-betweenmb-4">
<h2className="text-basefont-boldtext-gray-900">TripsAwaitingAllocation</h2>
<buttononClick={()=>router.push('/trips')}className="text-emerald-500text-smfont-mediumhover:text-emerald-600">ViewAll→</button>
</div>
<divclassName="space-y-3">
{approvedRequests.length===0?(
<divclassName="text-centerpy-8text-gray-400">
<svgclassName="w-12h-12mx-automb-2text-gray-300"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M95H7a22000-22v12a2200022h10a220002-2V7a22000-2-2h-2M95a2200022h2a220002-2M95a220012-2h2a2200122"/>
</svg>
<pclassName="text-sm">Notripsawaitingallocation</p>
</div>
):approvedRequests.slice(0,4).map((trip:any,idx:number)=>{
constsl=stateLabel[trip.state]||{label:trip.state,color:'bg-gray-100text-gray-700'}
return(
<divkey={trip.id}className="flexflex-colsm:flex-rowitems-startsm:items-centergap-3p-4bg-gray-50rounded-lghover:shadow-mdtransition-shadow">
<spanclassName="text-xstext-gray-500sm:w-24">{trip.requestNumber||trip.id?.slice(0,8)}</span>
<divclassName={`w-12h-12rounded-fullbg-gradient-to-br${gradients[idx%gradients.length]}flex-shrink-0flexitems-centerjustify-center`}>
<spanclassName="text-whitefont-bold">{trip.requester?.name?.charAt(0)?.toUpperCase()||'T'}</span>
</div>
<divclassName="flex-1min-w-0">
<pclassName="font-mediumtext-gray-900text-sm">{trip.requester?.name||'Unknown'}</p>
<pclassName="text-xstext-gray-500truncate">→{trip.destination}</p>
</div>
<spanclassName={`px-3py-1${sl.color}text-xsfont-mediumrounded-full`}>{sl.label}</span>
<buttononClick={()=>{setSelectedRequest(trip);setShowAssignModal(true);setAssignmentData({vehicleId:'',driverId:'',estimatedFuelCost:'',estimatedDistance:''})}}
className="px-3py-1.5bg-emerald-600text-whitetext-xsrounded-lghover:bg-emerald-700flex-shrink-0">
Assign
</button>
</div>
)
})}
</div>
</div>

{/*RightColumn*/}
<divclassName="space-y-6">
{/*PendingMaintenanceAlerts*/}
<divclassName="bg-whiterounded-xlp-6borderborder-gray-200">
<divclassName="flexitems-centerjustify-betweenmb-4">
<h2className="text-basefont-boldtext-gray-900">MaintenanceAlerts</h2>
{pendingMaintenance.length>0&&(
<spanclassName="px-2py-1bg-red-100text-red-600text-xsfont-boldrounded">{pendingMaintenance.length}NEW</span>
)}
</div>
<divclassName="space-y-3">
{pendingMaintenance.length===0?(
<pclassName="text-smtext-gray-400text-centerpy-4">Nopendingalerts</p>
):pendingMaintenance.map((item:any)=>(
<divkey={item.id}className="flexitems-startgap-3">
<divclassName="w-2h-2bg-orange-500rounded-fullmt-2flex-shrink-0"></div>
<divclassName="flex-1">
<pclassName="font-mediumtext-gray-900text-sm">{item.issueDescription?.slice(0,50)||'MaintenanceRequired'}</p>
<pclassName="text-xstext-gray-500">{item.vehicle?.plateNumber||'Vehicle'}•{item.priority}</p>
<pclassName="text-xstext-gray-400mt-1">{item.createdAt?newDate(item.createdAt).toLocaleString():''}</p>
</div>
</div>
))}
</div>
</div>

{/*LiveMapPlaceholder*/}
<divclassName="bg-whiterounded-xlp-6borderborder-gray-200">
<divclassName="flexitems-centerjustify-betweenmb-3">
<h2className="text-basefont-boldtext-gray-900">LiveOperations</h2>
<spanclassName="text-xstext-gray-500">{vehicleStats.inUse}ActiveUnits</span>
</div>
<divclassName="h-48bg-gradient-to-brfrom-blue-50to-emerald-50rounded-lgflexitems-centerjustify-center">
<divclassName="text-center">
<svgclassName="w-12h-12text-gray-400mx-automb-2"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M920l-5.447-2.724A11001316.382V5.618a110011.447-.894L97m013l6-3m-63V7m610l4.5532.276A110002118.382V7.618a11000-.553-.894L154m013V4m00L97"/>
</svg>
<pclassName="text-gray-500text-sm">Real-timeVehicleTracking</p>
<pclassName="text-gray-400text-xsmt-1">GPSintegrationactive</p>
</div>
</div>
</div>
</div>
</div>

{/*AssignModal*/}
{showAssignModal&&selectedRequest&&(
<divclassName="fixedinset-0bg-black/50flexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-2xlshadow-2xlmax-w-mdw-fullp-6">
<divclassName="flexjustify-betweenmb-4">
<h3className="text-xlfont-boldtext-gray-800">AssignVehicle&Driver</h3>
<buttononClick={()=>setShowAssignModal(false)}className="p-2hover:bg-gray-100rounded-lg">
<svgclassName="w-5h-5"fill="none"stroke="currentColor"viewBox="002424"><pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M618L186M66l1212"/></svg>
</button>
</div>
<pclassName="text-smtext-gray-500mb-4">Trip:<spanclassName="font-mediumtext-gray-800">{selectedRequest.requestNumber}</span>→{selectedRequest.destination}</p>
<divclassName="space-y-4">
<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-1">Vehicle</label>
<selectvalue={assignmentData.vehicleId}onChange={e=>setAssignmentData({...assignmentData,vehicleId:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500">
<optionvalue="">Selectvehicle...</option>
{availableVehicles.map((v:any)=>(
<optionkey={v.id}value={v.id}>{v.make}{v.model}({v.plateNumber})</option>
))}
</select>
</div>
<div>
<labelclassName="blocktext-smfont-mediumtext-gray-700mb-1">Driver</label>
<selectvalue={assignmentData.driverId}onChange={e=>setAssignmentData({...assignmentData,driverId:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500">
<optionvalue="">Selectdriver...</option>
{availableDrivers.map((d:any)=>(
<optionkey={d.id}value={d.id}>{d.user?.name||d.name}({d.licenseNumber})</option>
))}
</select>
</div>

{/*Fuel&DistanceSection*/}
<divclassName="border-tborder-gray-100pt-4">
<divclassName="flexitems-centergap-2mb-3">
<svgclassName="w-4h-4text-orange-500"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={1.5}d="M1310V3L414h7v7l9-11h-7z"/>
</svg>
<spanclassName="text-smfont-semiboldtext-gray-700">Fuel&DistanceEstimate</span>
</div>
<divclassName="gridgrid-cols-2gap-3">
<div>
<labelclassName="blocktext-xsfont-mediumtext-gray-600mb-1">Est.FuelCost(ETB)</label>
<input
type="number"
min="0"
placeholder="e.g.500"
value={assignmentData.estimatedFuelCost}
onChange={e=>setAssignmentData({...assignmentData,estimatedFuelCost:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-orange-400"
/>
</div>
<div>
<labelclassName="blocktext-xsfont-mediumtext-gray-600mb-1">Est.Distance(km)</label>
<input
type="number"
min="0"
placeholder="e.g.120"
value={assignmentData.estimatedDistance}
onChange={e=>setAssignmentData({...assignmentData,estimatedDistance:e.target.value})}
className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-orange-400"
/>
</div>
</div>
</div>
</div>
<divclassName="flexgap-3mt-6">
<buttononClick={()=>setShowAssignModal(false)}className="flex-1px-4py-2borderborder-gray-300rounded-lgtext-smhover:bg-gray-50">Cancel</button>
<buttononClick={handleAssign}className="flex-1px-4py-2bg-emerald-600text-whiterounded-lgtext-smfont-mediumhover:bg-emerald-700">Assign</button>
</div>
</div>
</div>
)}
</div>
)
}



