apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fleet-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fleet-management-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend:3000/api/v1

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fleet-management
spec:
  selector:
    app: frontend
  ports:
    - port: 3010
      targetPort: 3000
