'useclient'

import{useState,useEffect}from'react'
import{maintenanceApi}from'@/lib/api'

exportdefaultfunctionMaintenancePage(){
const[searchQuery,setSearchQuery]=useState('')
const[statusFilter,setStatusFilter]=useState('all')
const[showDetailsModal,setShowDetailsModal]=useState(false)
const[selectedMaintenance,setSelectedMaintenance]=useState<any>(null)
const[showApproveModal,setShowApproveModal]=useState(false)
const[approveTarget,setApproveTarget]=useState<any>(null)
const[scheduleNotes,setScheduleNotes]=useState('')
const[estimatedCost,setEstimatedCost]=useState('')
const[approving,setApproving]=useState(false)
const[showToast,setShowToast]=useState(false)
const[toastMessage,setToastMessage]=useState('')
const[toastType,setToastType]=useState<'success'|'error'>('success')
const[maintenanceList,setMaintenanceList]=useState<any[]>([])
const[loading,setLoading]=useState(true)
const[error,setError]=useState<string|null>(null)

useEffect(()=>{
loadMaintenance()
},[])

constloadMaintenance=async()=>{
try{
setError(null)
constdata=awaitmaintenanceApi.getAllMaintenanceRequests()
setMaintenanceList(Array.isArray(data)?data:[])
}catch(err:any){
setError(err?.message||'Failedtoloadmaintenancerecords')
}finally{
setLoading(false)
}
}

constgetStatusDisplay=(status:string)=>{
switch((status||'').toLowerCase()){
case'submitted':return{label:'Submitted',color:'bg-orange-100text-orange-700'}
case'underinspection':return{label:'UnderInspection',color:'bg-yellow-100text-yellow-700'}
case'estimateprovided':return{label:'EstimateProvided',color:'bg-purple-100text-purple-700'}
case'budgetapproved':return{label:'BudgetApproved',color:'bg-blue-100text-blue-700'}
case'inprogress':
case'inprogress':return{label:'InProgress',color:'bg-blue-100text-blue-700'}
case'completed':return{label:'Completed',color:'bg-emerald-100text-emerald-700'}
case'rejected':return{label:'Rejected',color:'bg-red-100text-red-700'}
case'pending':return{label:'Pending',color:'bg-gray-100text-gray-700'}
case'scheduled':return{label:'Scheduled',color:'bg-yellow-100text-yellow-700'}
default:return{label:status||'Unknown',color:'bg-gray-100text-gray-700'}
}
}

constshowNotification=(message:string,type:'success'|'error'='success')=>{
setToastMessage(message)
setToastType(type)
setShowToast(true)
setTimeout(()=>setShowToast(false),3000)
}

consthandleViewDetails=(maintenance:any)=>{
setSelectedMaintenance(maintenance)
setShowDetailsModal(true)
}

consthandleApprove=(maintenance:any)=>{
setApproveTarget(maintenance)
setScheduleNotes('')
setEstimatedCost('')
setShowApproveModal(true)
}

consthandleApproveSubmit=async()=>{
if(!approveTarget)return
setApproving(true)
try{
consttoken=typeofwindow!=='undefined'?localStorage.getItem('accessToken')||localStorage.getItem('access_token'):null
//Step1:inspect(movestoEstimateProvided)
awaitfetch(`http://localhost:3000/api/v1/maintenance/${approveTarget.id}/inspect`,{
method:'POST',
headers:{'Content-Type':'application/json',Authorization:`Bearer${token}`},
body:JSON.stringify({inspectionNotes:scheduleNotes||'Approvedbydeploymentoffice',estimatedCost:Number(estimatedCost)||0})
})
//Step2:approve-budget(movestoBudgetApproved—drivercannowstart)
awaitfetch(`http://localhost:3000/api/v1/maintenance/${approveTarget.id}/approve-budget`,{
method:'POST',
headers:{Authorization:`Bearer${token}`}
})
showNotification('Maintenanceapproved—driverwillbenotifiedtotakevehicleforservice','success')
setShowApproveModal(false)
loadMaintenance()
}catch(err:any){
showNotification(err.message||'Failedtoapprove','error')
}finally{
setApproving(false)
}
}

consthandleReject=async(maintenance:any)=>{
constreason=prompt('Reasonforrejection:')
if(!reason)return
try{
consttoken=typeofwindow!=='undefined'?localStorage.getItem('accessToken')||localStorage.getItem('access_token'):null
awaitfetch(`http://localhost:3000/api/v1/maintenance/${maintenance.id}/reject`,{
method:'POST',
headers:{'Content-Type':'application/json',Authorization:`Bearer${token}`},
body:JSON.stringify({reason})
})
showNotification('Maintenancerequestrejected','success')
loadMaintenance()
}catch(err:any){
showNotification(err.message||'Failedtoreject','error')
}
}

constgetFilteredMaintenance=()=>{
returnmaintenanceList.filter(maintenance=>{
constvehicleName=maintenance.vehicleName||maintenance.vehicle?.model||maintenance.vehicle?.name||''
constvehiclePlate=maintenance.vehiclePlate||maintenance.vehicle?.plateNumber||maintenance.vehicle?.plate||''
constmatchesSearch=searchQuery===''||
(maintenance.id||'').toLowerCase().includes(searchQuery.toLowerCase())||
vehicleName.toLowerCase().includes(searchQuery.toLowerCase())||
vehiclePlate.toLowerCase().includes(searchQuery.toLowerCase())||
(maintenance.type||maintenance.maintenanceType||'').toLowerCase().includes(searchQuery.toLowerCase())
constmatchesStatus=statusFilter==='all'||
(maintenance.status||'').toLowerCase().replace(/\s/g,'')===statusFilter.toLowerCase().replace(/\s/g,'')
returnmatchesSearch&&matchesStatus
})
}

constfilteredMaintenance=getFilteredMaintenance()

conststats={
total:maintenanceList.length,
submitted:maintenanceList.filter(m=>(m.status||'').toLowerCase()==='submitted').length,
inProgress:maintenanceList.filter(m=>['inprogress','inprogress'].includes((m.status||'').toLowerCase())).length,
completed:maintenanceList.filter(m=>(m.status||'').toLowerCase()==='completed').length,
rejected:maintenanceList.filter(m=>(m.status||'').toLowerCase()==='rejected').length,
}

return(
<divclassName="p-4sm:p-6lg:p-8">
{showToast&&(
<divclassName="fixedtop-4right-4z-50">
<divclassName={`px-6py-3rounded-lgshadow-lg${toastType==='success'?'bg-emerald-600':'bg-red-600'}text-white`}>
{toastMessage}
</div>
</div>
)}

<divclassName="mb-6">
<h1className="text-2xlmd:text-3xlfont-boldtext-gray-800">MaintenanceManagement</h1>
<pclassName="text-smtext-gray-600mt-1">Trackandmanagevehiclemaintenanceschedules</p>
</div>

<divclassName="gridgrid-cols-2lg:grid-cols-5gap-3sm:gap-4lg:gap-6mb-6">
<divclassName="bg-whiterounded-xlp-4md:p-6borderborder-gray-200">
<spanclassName="text-xsmd:text-smtext-gray-600">Total</span>
<h3className="text-2xlmd:text-3xlfont-boldtext-gray-900mt-2">{stats.total}</h3>
</div>
<divclassName="bg-whiterounded-xlp-4md:p-6borderborder-gray-200">
<spanclassName="text-xsmd:text-smtext-gray-600">Submitted</span>
<h3className="text-2xlmd:text-3xlfont-boldtext-orange-600mt-2">{stats.submitted}</h3>
</div>
<divclassName="bg-whiterounded-xlp-4md:p-6borderborder-gray-200">
<spanclassName="text-xsmd:text-smtext-gray-600">InProgress</span>
<h3className="text-2xlmd:text-3xlfont-boldtext-blue-600mt-2">{stats.inProgress}</h3>
</div>
<divclassName="bg-whiterounded-xlp-4md:p-6borderborder-gray-200">
<spanclassName="text-xsmd:text-smtext-gray-600">Completed</span>
<h3className="text-2xlmd:text-3xlfont-boldtext-emerald-600mt-2">{stats.completed}</h3>
</div>
<divclassName="bg-whiterounded-xlp-4md:p-6borderborder-gray-200">
<spanclassName="text-xsmd:text-smtext-gray-600">Rejected</span>
<h3className="text-2xlmd:text-3xlfont-boldtext-red-600mt-2">{stats.rejected}</h3>
</div>
</div>

<divclassName="bg-whiterounded-xlp-4sm:p-6borderborder-gray-200mb-6">
<divclassName="flexflex-colsm:flex-rowitems-stretchsm:items-centergap-3sm:gap-4">
<divclassName="flex-1relative">
<input
type="text"
placeholder="SearchbyID,vehicle,ortype..."
value={searchQuery}
onChange={(e)=>setSearchQuery(e.target.value)}
className="w-fullpl-10pr-4py-2text-smborderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500outline-none"
/>
<svgclassName="w-5h-5text-gray-400absoluteleft-3top-1/2-translate-y-1/2"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={2}d="M2121l-6-6m2-5a77011-14077001140z"/>
</svg>
</div>
<select
value={statusFilter}
onChange={(e)=>setStatusFilter(e.target.value)}
className="px-4py-2text-smborderborder-gray-300rounded-lgfocus:ring-2focus:ring-emerald-500outline-none"
>
<optionvalue="all">AllStatus</option>
<optionvalue="submitted">Submitted</option>
<optionvalue="underinspection">UnderInspection</option>
<optionvalue="estimateprovided">EstimateProvided</option>
<optionvalue="budgetapproved">BudgetApproved</option>
<optionvalue="inprogress">InProgress</option>
<optionvalue="completed">Completed</option>
<optionvalue="rejected">Rejected</option>
</select>
<buttononClick={loadMaintenance}className="px-4py-2bg-emerald-500text-whiterounded-lgtext-smfont-mediumhover:bg-emerald-600transition-colors">
Refresh
</button>
</div>
</div>

{loading&&(
<divclassName="space-y-4">
{[1,2,3].map(i=>(
<divkey={i}className="bg-whiterounded-xlborderborder-gray-200p-4md:p-6animate-pulse">
<divclassName="h-4bg-gray-200roundedw-1/4mb-3"></div>
<divclassName="h-3bg-gray-200roundedw-1/2"></div>
</div>
))}
</div>
)}

{error&&!loading&&(
<divclassName="bg-whiterounded-xlp-12text-centerborderborder-red-200">
<pclassName="text-red-600mb-4">{error}</p>
<buttononClick={loadMaintenance}className="px-4py-2bg-emerald-500text-whiterounded-lghover:bg-emerald-600">
Retry
</button>
</div>
)}

{!loading&&!error&&(
<divclassName="space-y-4">
{filteredMaintenance.map((maintenance)=>{
constvehicleName=maintenance.vehicleName||maintenance.vehicle?.model||maintenance.vehicle?.name||'UnknownVehicle'
constvehiclePlate=maintenance.vehiclePlate||maintenance.vehicle?.plateNumber||maintenance.vehicle?.plate||''
constmaintenanceType=maintenance.type||maintenance.maintenanceType||maintenance.priority||'N/A'
constdescription=maintenance.description||maintenance.reason||maintenance.issueDescription||''
constscheduledDate=maintenance.scheduledDate||maintenance.scheduledAt||''
constrequestedBy=maintenance.requestedBy||maintenance.requestedByUser?.name||maintenance.reportedBy?.user?.name||maintenance.reportedBy?.name||'N/A'
const{label:statusLabel,color:statusColor}=getStatusDisplay(maintenance.status)
return(
<divkey={maintenance.id}className="bg-whiterounded-xlborderborder-gray-200p-4md:p-6hover:shadow-lgtransition-shadow">
<divclassName="flexflex-collg:flex-rowlg:items-centergap-4">
<divclassName="flex-1">
<divclassName="flexitems-startjustify-betweenmb-3">
<div>
<h3className="text-lgfont-boldtext-gray-900">{maintenance.id}</h3>
<pclassName="text-smtext-gray-600">{vehicleName}{vehiclePlate?`•${vehiclePlate}`:''}</p>
</div>
<spanclassName={`px-3py-1rounded-fulltext-xsfont-medium${statusColor}`}>
{statusLabel}
</span>
</div>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-3mb-3text-sm">
<spanclassName="text-gray-700"><spanclassName="font-medium">Type:</span>{maintenanceType}</span>
{scheduledDate&&<spanclassName="text-gray-700"><spanclassName="font-medium">Scheduled:</span>{scheduledDate}</span>}
<spanclassName="text-gray-700"><spanclassName="font-medium">Requestedby:</span>{requestedBy}</span>
</div>
{description&&(
<divclassName="text-smtext-gray-700">
<spanclassName="font-medium">Reason:</span>{description}
</div>
)}
</div>
<divclassName="flexgap-2">
<button
onClick={()=>handleViewDetails(maintenance)}
className="px-4py-2bg-gray-100text-gray-700rounded-lgtext-smfont-mediumhover:bg-gray-200transition-colors"
>
ViewDetails
</button>
{(maintenance.status==='Submitted')&&(
<button
onClick={()=>handleApprove(maintenance)}
className="px-4py-2bg-emerald-600text-whiterounded-lgtext-smfont-mediumhover:bg-emerald-700transition-colors"
>
Approve&Schedule
</button>
)}
{(maintenance.status==='Submitted'||maintenance.status==='EstimateProvided')&&(
<button
onClick={()=>handleReject(maintenance)}
className="px-4py-2bg-red-600text-whiterounded-lgtext-smfont-mediumhover:bg-red-700transition-colors"
>
Reject
</button>
)}
</div>
</div>
</div>
)
})}
</div>
)}

{!loading&&!error&&filteredMaintenance.length===0&&(
<divclassName="bg-whiterounded-xlp-12text-centerborderborder-gray-200">
<h3className="text-lgfont-mediumtext-gray-900mb-2">Nomaintenancerecordsfound</h3>
<pclassName="text-gray-500">Tryadjustingyoursearchorfiltercriteria</p>
</div>
)}

{showApproveModal&&approveTarget&&(
<divclassName="fixedinset-0bg-black/50flexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-xlshadow-2xlmax-w-mdw-fullp-6">
<h3className="text-lgfont-boldtext-gray-900mb-1">Approve&ScheduleMaintenance</h3>
<pclassName="text-smtext-gray-500mb-4">Vehicle:{approveTarget.vehicle?.plateNumber||'N/A'}—{approveTarget.issueDescription}</p>
<divclassName="space-y-3">
<div>
<labelclassName="blocktext-xsfont-mediumtext-gray-600mb-1">EstimatedCost(ETB)</label>
<inputtype="number"min="0"value={estimatedCost}onChange={e=>setEstimatedCost(e.target.value)}
placeholder="e.g.2000"className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500"/>
</div>
<div>
<labelclassName="blocktext-xsfont-mediumtext-gray-600mb-1">ScheduleNotes(optional)</label>
<textarearows={2}value={scheduleNotes}onChange={e=>setScheduleNotes(e.target.value)}
placeholder="e.g.TakevehicletoworkshoponMondaymorning"
className="w-fullpx-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500resize-none"/>
</div>
</div>
<divclassName="flexgap-3mt-5">
<buttononClick={()=>setShowApproveModal(false)}className="flex-1px-4py-2borderborder-gray-300rounded-lgtext-smhover:bg-gray-50">Cancel</button>
<buttononClick={handleApproveSubmit}disabled={approving}
className="flex-1px-4py-2bg-emerald-600text-whiterounded-lgtext-smfont-semiboldhover:bg-emerald-700disabled:opacity-50">
{approving?'Approving...':'Approve&NotifyDriver'}
</button>
</div>
</div>
</div>
)}

{showDetailsModal&&selectedMaintenance&&(
<divclassName="fixedinset-0bg-blackbg-opacity-50backdrop-blur-smflexitems-centerjustify-centerz-50p-4">
<divclassName="bg-whiterounded-2xlshadow-2xlmax-w-lgw-fullp-6max-h-[90vh]overflow-y-auto">
<divclassName="flexitems-centerjustify-betweenmb-6">
<h3className="text-xlfont-boldtext-gray-800">MaintenanceDetails</h3>
<buttononClick={()=>setShowDetailsModal(false)}className="p-2hover:bg-gray-100rounded-lg">
<svgclassName="w-5h-5"fill="none"stroke="currentColor"viewBox="002424">
<pathstrokeLinecap="round"strokeLinejoin="round"strokeWidth={2}d="M618L186M66l1212"/>
</svg>
</button>
</div>
<divclassName="mb-4">
<spanclassName={`px-4py-2rounded-lgtext-smfont-medium${getStatusDisplay(selectedMaintenance.status).color}`}>
{getStatusDisplay(selectedMaintenance.status).label}
</span>
</div>
<divclassName="gridgrid-cols-1md:grid-cols-2gap-4mb-6">
<div><spanclassName="text-smtext-gray-600">RequestID</span><pclassName="font-medium">{selectedMaintenance.id}</p></div>
<div><spanclassName="text-smtext-gray-600">Type</span><pclassName="font-medium">{selectedMaintenance.type||selectedMaintenance.maintenanceType||'N/A'}</p></div>
<div><spanclassName="text-smtext-gray-600">Vehicle</span><pclassName="font-medium">{selectedMaintenance.vehicleName||selectedMaintenance.vehicle?.model||'N/A'}</p></div>
<div><spanclassName="text-smtext-gray-600">Scheduled</span><pclassName="font-medium">{selectedMaintenance.scheduledDate||selectedMaintenance.scheduledAt||'N/A'}</p></div>
</div>
{(selectedMaintenance.description||selectedMaintenance.reason)&&(
<divclassName="mb-6">
<h4className="font-semiboldtext-gray-800mb-2">Reason</h4>
<pclassName="text-gray-700bg-gray-50rounded-lgp-4">{selectedMaintenance.description||selectedMaintenance.reason}</p>
</div>
)}
<buttononClick={()=>setShowDetailsModal(false)}className="w-fullpx-4py-2borderborder-gray-300rounded-lghover:bg-gray-50">
Close
</button>
</div>
</div>
)}
</div>
)
}


