'useclient'

import{useState,useEffect}from'react'
import{tripApi,vehicleApi,driverApi,maintenanceApi}from'@/lib/api'

exportdefaultfunctionReportsPage(){
const[selectedReport,setSelectedReport]=useState('trip-summary')
const[dateRange,setDateRange]=useState('last-30-days')
const[customStartDate,setCustomStartDate]=useState('')
const[customEndDate,setCustomEndDate]=useState('')
const[loading,setLoading]=useState(true)
const[toast,setToast]=useState<{message:string;type:'success'|'error'|'info'}|null>(null)

//Realdata
const[allTrips,setAllTrips]=useState<any[]>([])
const[allVehicles,setAllVehicles]=useState<any[]>([])
const[allDrivers,setAllDrivers]=useState<any[]>([])
const[allMaintenance,setAllMaintenance]=useState<any[]>([])

useEffect(()=>{
constload=async()=>{
setLoading(true)
const[trips,vehicles,drivers,maintenance]=awaitPromise.all([
tripApi.getAllTrips().catch(()=>[]),
vehicleApi.getAllVehicles().catch(()=>[]),
driverApi.getAllDrivers().catch(()=>[]),
maintenanceApi.getAllMaintenanceRequests().catch(()=>[]),
])
setAllTrips(Array.isArray(trips)?trips:[])
setAllVehicles(Array.isArray(vehicles)?vehicles:[])
setAllDrivers(Array.isArray(drivers)?drivers:[])
setAllMaintenance(Array.isArray(maintenance)?maintenance:[])
setLoading(false)
}
load()
},[])

//Filtertripsbyselecteddaterange
constgetDateBounds=()=>{
constnow=newDate()
conststart=newDate()
if(dateRange==='today'){start.setHours(0,0,0,0)}
elseif(dateRange==='yesterday'){start.setDate(now.getDate()-1);start.setHours(0,0,0,0)}
elseif(dateRange==='last-7-days'){start.setDate(now.getDate()-7)}
elseif(dateRange==='last-30-days'){start.setDate(now.getDate()-30)}
elseif(dateRange==='this-month'){start.setDate(1);start.setHours(0,0,0,0)}
elseif(dateRange==='last-month'){start.setMonth(now.getMonth()-1);start.setDate(1);start.setHours(0,0,0,0)}
elseif(dateRange==='this-quarter'){start.setMonth(Math.floor(now.getMonth()/3)*3);start.setDate(1)}
elseif(dateRange==='this-year'){start.setMonth(0);start.setDate(1);start.setHours(0,0,0,0)}
elseif(dateRange==='custom'){
return{start:customStartDate?newDate(customStartDate):newDate(0),end:customEndDate?newDate(customEndDate):now}
}
return{start,end:now}
}

const{start:rangeStart,end:rangeEnd}=getDateBounds()
constfilteredTrips=allTrips.filter((t:any)=>{
constd=newDate(t.createdAt)
returnd>=rangeStart&&d<=rangeEnd
})

//Tripsummarystats
consttotalTrips=filteredTrips.length
constcompletedTrips=filteredTrips.filter((t:any)=>['COMPLETED','completed'].includes(t.state||t.status||'')).length
constinProgressTrips=filteredTrips.filter((t:any)=>['IN_PROGRESS','in_progress'].includes(t.state||t.status||'')).length
constcancelledTrips=filteredTrips.filter((t:any)=>['REJECTED','rejected','CANCELLED','cancelled'].includes(t.state||t.status||'')).length
constcompletionRate=totalTrips>0?Math.round((completedTrips/totalTrips)*100):0

//Monthlytrend(last6months)
constmonthlyTrend=Array.from({length:6},(_,i)=>{
constd=newDate();d.setMonth(d.getMonth()-5+i)
constcount=allTrips.filter((t:any)=>{
consttd=newDate(t.createdAt)
returntd.getFullYear()===d.getFullYear()&&td.getMonth()===d.getMonth()
}).length
return{label:d.toLocaleString('default',{month:'short'}),count}
})
constmaxMonthly=Math.max(...monthlyTrend.map(m=>m.count),1)

//Vehicleutilization
consttotalVehicles=allVehicles.length
constactiveVehicles=allVehicles.filter((v:any)=>v.status==='Active').length
constinUseVehicles=allVehicles.filter((v:any)=>['InUse','OnTrip'].includes(v.status)).length
constmaintenanceVehicles=allVehicles.filter((v:any)=>['UnderMaintenance','Maintenance'].includes(v.status)).length
constutilizationRate=totalVehicles>0?Math.round((inUseVehicles/totalVehicles)*100):0

//Driverperformance
consttotalDrivers=allDrivers.length
constactiveDrivers=allDrivers.filter((d:any)=>d.status==='Available'||d.isAvailable).length
constdriverTrips=allDrivers.map((d:any)=>({
name:d.user?.name||d.name||'Unknown',
license:d.licenseNumber||'N/A',
trips:filteredTrips.filter((t:any)=>t.driver?.id===d.id||t.driverId===d.id).length,
status:d.status||(d.isAvailable?'Available':'Busy'),
})).sort((a,b)=>b.trips-a.trips).slice(0,5)

//Maintenancestats
consttotalMaint=allMaintenance.length
constpendingMaint=allMaintenance.filter((m:any)=>['Submitted','UnderInspection'].includes(m.status)).length
constcompletedMaint=allMaintenance.filter((m:any)=>m.status==='Completed').length
consturgentMaint=allMaintenance.filter((m:any)=>m.priority==='Critical'||m.priority==='High').length

constreportCategories=[
{id:'trip-summary',name:'TripSummary',color:'emerald'},
{id:'vehicle-utilization',name:'VehicleUtilization',color:'blue'},
{id:'driver-performance',name:'DriverPerformance',color:'purple'},
{id:'maintenance-report',name:'MaintenanceReport',color:'orange'},
]

constdateRanges=[
{value:'today',label:'Today'},
{value:'last-7-days',label:'Last7Days'},
{value:'last-30-days',label:'Last30Days'},
{value:'this-month',label:'ThisMonth'},
{value:'last-month',label:'LastMonth'},
{value:'this-quarter',label:'ThisQuarter'},
{value:'this-year',label:'ThisYear'},
{value:'custom',label:'CustomRange'},
]

if(loading)return(
<divclassName="flexitems-centerjustify-centerh-64">
<divclassName="animate-spinrounded-fullh-12w-12border-b-4border-emerald-600"></div>
</div>
)

return(
<divclassName="p-4md:p-6space-y-6">
{toast&&(
<divclassName="fixedtop-4right-4z-50">
<divclassName={`px-5py-3rounded-lgshadow-lgtext-whitetext-sm${toast.type==='success'?'bg-emerald-600':toast.type==='error'?'bg-red-600':'bg-blue-600'}`}>
{toast.message}
</div>
</div>
)}

{/*Header*/}
<divclassName="flexflex-colsm:flex-rowsm:items-centersm:justify-betweengap-3">
<div>
<h1className="text-2xlfont-boldtext-gray-900">Reports&Analytics</h1>
<pclassName="text-smtext-gray-500mt-1">Livedatafromfleetoperations</p>
</div>
</div>

{/*Filters*/}
<divclassName="bg-whiterounded-xlborderborder-gray-200p-4flexflex-wrapgap-3items-end">
<div>
<labelclassName="blocktext-xsfont-semiboldtext-gray-600mb-1">DateRange</label>
<selectvalue={dateRange}onChange={e=>setDateRange(e.target.value)}
className="px-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500">
{dateRanges.map(r=><optionkey={r.value}value={r.value}>{r.label}</option>)}
</select>
</div>
{dateRange==='custom'&&(
<>
<div>
<labelclassName="blocktext-xsfont-semiboldtext-gray-600mb-1">Start</label>
<inputtype="date"value={customStartDate}onChange={e=>setCustomStartDate(e.target.value)}
className="px-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500"/>
</div>
<div>
<labelclassName="blocktext-xsfont-semiboldtext-gray-600mb-1">End</label>
<inputtype="date"value={customEndDate}onChange={e=>setCustomEndDate(e.target.value)}
className="px-3py-2borderborder-gray-300rounded-lgtext-smoutline-nonefocus:ring-2focus:ring-emerald-500"/>
</div>
</>
)}
</div>

{/*ReportTabs*/}
<divclassName="flexflex-wrapgap-2">
{reportCategories.map(c=>(
<buttonkey={c.id}onClick={()=>setSelectedReport(c.id)}
className={`px-4py-2rounded-lgtext-smfont-mediumtransition-colors${selectedReport===c.id?'bg-emerald-600text-white':'bg-whiteborderborder-gray-200text-gray-700hover:bg-gray-50'}`}>
{c.name}
</button>
))}
</div>

{/*TripSummary*/}
{selectedReport==='trip-summary'&&(
<divclassName="space-y-6">
<divclassName="gridgrid-cols-2lg:grid-cols-4gap-4">
{[
{label:'TotalTrips',value:totalTrips,sub:`inselectedperiod`},
{label:'Completed',value:completedTrips,sub:`${completionRate}%completionrate`},
{label:'InProgress',value:inProgressTrips,sub:'Currentlyactive'},
{label:'Cancelled',value:cancelledTrips,sub:totalTrips>0?`${Math.round(cancelledTrips/totalTrips*100)}%cancellation`:'0%'},
].map(s=>(
<divkey={s.label}className="bg-whiterounded-xlborderborder-gray-200p-5">
<pclassName="text-smtext-gray-500mb-1">{s.label}</p>
<pclassName="text-3xlfont-boldtext-gray-900">{s.value}</p>
<pclassName="text-xstext-gray-500mt-1">{s.sub}</p>
</div>
))}
</div>

{/*Monthlytrend*/}
<divclassName="bg-whiterounded-xlborderborder-gray-200p-6">
<h3className="text-basefont-boldtext-gray-900mb-4">MonthlyTripTrend(Last6Months)</h3>
<divclassName="flexitems-endgap-3h-40">
{monthlyTrend.map((m,i)=>(
<divkey={i}className="flex-1flexflex-colitems-centergap-1">
<spanclassName="text-xstext-gray-500">{m.count}</span>
<divclassName="w-fullbg-emerald-500rounded-ttransition-all"
style={{height:`${(m.count/maxMonthly)*120}px`,minHeight:m.count>0?'4px':'0'}}></div>
<spanclassName="text-xstext-gray-400">{m.label}</span>
</div>
))}
</div>
</div>

{/*Recenttripstable*/}
<divclassName="bg-whiterounded-xlborderborder-gray-200p-6">
<h3className="text-basefont-boldtext-gray-900mb-4">RecentTrips({filteredTrips.length})</h3>
<divclassName="overflow-x-auto">
<tableclassName="w-fulltext-sm">
<thead><trclassName="border-bborder-gray-100text-lefttext-xstext-gray-500">
<thclassName="pb-2pr-4">ID</th><thclassName="pb-2pr-4">Requester</th>
<thclassName="pb-2pr-4">Destination</th><thclassName="pb-2pr-4">Status</th><thclassName="pb-2">Date</th>
</tr></thead>
<tbody>
{filteredTrips.slice(0,10).map((t:any)=>(
<trkey={t.id}className="border-bborder-gray-50hover:bg-gray-50">
<tdclassName="py-2pr-4text-xstext-gray-400">{t.requestNumber||t.id?.slice(0,8)}</td>
<tdclassName="py-2pr-4font-mediumtext-gray-800">{t.requester?.name||'N/A'}</td>
<tdclassName="py-2pr-4text-gray-600truncatemax-w-[140px]">{t.destination||'N/A'}</td>
<tdclassName="py-2pr-4"><spanclassName="px-2py-0.5bg-gray-100text-gray-700roundedtext-xs">{t.state||t.status}</span></td>
<tdclassName="py-2text-xstext-gray-400">{t.createdAt?newDate(t.createdAt).toLocaleDateString():'N/A'}</td>
</tr>
))}
{filteredTrips.length===0&&<tr><tdcolSpan={5}className="py-8text-centertext-gray-400">Notripsinselectedperiod</td></tr>}
</tbody>
</table>
</div>
</div>
</div>
)}

{/*VehicleUtilization*/}
{selectedReport==='vehicle-utilization'&&(
<divclassName="space-y-6">
<divclassName="gridgrid-cols-2lg:grid-cols-4gap-4">
{[
{label:'TotalFleet',value:totalVehicles},
{label:'Available',value:activeVehicles},
{label:'InUse',value:inUseVehicles},
{label:'Maintenance',value:maintenanceVehicles},
].map(s=>(
<divkey={s.label}className="bg-whiterounded-xlborderborder-gray-200p-5">
<pclassName="text-smtext-gray-500mb-1">{s.label}</p>
<pclassName="text-3xlfont-boldtext-gray-900">{s.value}</p>
{s.label==='InUse'&&<pclassName="text-xstext-gray-500mt-1">{utilizationRate}%utilization</p>}
</div>
))}
</div>
<divclassName="bg-whiterounded-xlborderborder-gray-200p-6">
<h3className="text-basefont-boldtext-gray-900mb-4">AllVehicles({allVehicles.length})</h3>
<divclassName="overflow-x-auto">
<tableclassName="w-fulltext-sm">
<thead><trclassName="border-bborder-gray-100text-lefttext-xstext-gray-500">
<thclassName="pb-2pr-4">Plate</th><thclassName="pb-2pr-4">Make/Model</th>
<thclassName="pb-2pr-4">Type</th><thclassName="pb-2">Status</th>
</tr></thead>
<tbody>
{allVehicles.map((v:any)=>(
<trkey={v.id}className="border-bborder-gray-50hover:bg-gray-50">
<tdclassName="py-2pr-4font-mediumtext-gray-800">{v.plateNumber}</td>
<tdclassName="py-2pr-4text-gray-600">{v.make}{v.model}</td>
<tdclassName="py-2pr-4text-gray-500">{v.type||'N/A'}</td>
<tdclassName="py-2"><spanclassName={`px-2py-0.5roundedtext-xsfont-medium${v.status==='Active'?'bg-green-100text-green-700':v.status==='OnTrip'||v.status==='InUse'?'bg-blue-100text-blue-700':'bg-orange-100text-orange-700'}`}>{v.status}</span></td>
</tr>
))}
{allVehicles.length===0&&<tr><tdcolSpan={4}className="py-8text-centertext-gray-400">Novehiclesfound</td></tr>}
</tbody>
</table>
</div>
</div>
</div>
)}

{/*DriverPerformance*/}
{selectedReport==='driver-performance'&&(
<divclassName="space-y-6">
<divclassName="gridgrid-cols-2lg:grid-cols-3gap-4">
{[
{label:'TotalDrivers',value:totalDrivers},
{label:'Available',value:activeDrivers},
{label:'Trips(period)',value:filteredTrips.filter((t:any)=>t.driverId||t.driver).length},
].map(s=>(
<divkey={s.label}className="bg-whiterounded-xlborderborder-gray-200p-5">
<pclassName="text-smtext-gray-500mb-1">{s.label}</p>
<pclassName="text-3xlfont-boldtext-gray-900">{s.value}</p>
</div>
))}
</div>
<divclassName="bg-whiterounded-xlborderborder-gray-200p-6">
<h3className="text-basefont-boldtext-gray-900mb-4">TopDriversbyTrips</h3>
<divclassName="overflow-x-auto">
<tableclassName="w-fulltext-sm">
<thead><trclassName="border-bborder-gray-100text-lefttext-xstext-gray-500">
<thclassName="pb-2pr-4">Driver</th><thclassName="pb-2pr-4">License</th>
<thclassName="pb-2pr-4">Trips</th><thclassName="pb-2">Status</th>
</tr></thead>
<tbody>
{driverTrips.map((d,i)=>(
<trkey={i}className="border-bborder-gray-50hover:bg-gray-50">
<tdclassName="py-2pr-4font-mediumtext-gray-800">{d.name}</td>
<tdclassName="py-2pr-4text-gray-500">{d.license}</td>
<tdclassName="py-2pr-4font-boldtext-emerald-600">{d.trips}</td>
<tdclassName="py-2"><spanclassName={`px-2py-0.5roundedtext-xs${d.status==='Available'?'bg-green-100text-green-700':'bg-gray-100text-gray-600'}`}>{d.status}</span></td>
</tr>
))}
{driverTrips.length===0&&<tr><tdcolSpan={4}className="py-8text-centertext-gray-400">Nodriversfound</td></tr>}
</tbody>
</table>
</div>
</div>
</div>
)}

{/*MaintenanceReport*/}
{selectedReport==='maintenance-report'&&(
<divclassName="space-y-6">
<divclassName="gridgrid-cols-2lg:grid-cols-4gap-4">
{[
{label:'TotalRequests',value:totalMaint},
{label:'Pending',value:pendingMaint},
{label:'Completed',value:completedMaint},
{label:'Urgent',value:urgentMaint},
].map(s=>(
<divkey={s.label}className="bg-whiterounded-xlborderborder-gray-200p-5">
<pclassName="text-smtext-gray-500mb-1">{s.label}</p>
<pclassName="text-3xlfont-boldtext-gray-900">{s.value}</p>
</div>
))}
</div>
<divclassName="bg-whiterounded-xlborderborder-gray-200p-6">
<h3className="text-basefont-boldtext-gray-900mb-4">MaintenanceRequests({allMaintenance.length})</h3>
<divclassName="overflow-x-auto">
<tableclassName="w-fulltext-sm">
<thead><trclassName="border-bborder-gray-100text-lefttext-xstext-gray-500">
<thclassName="pb-2pr-4">Vehicle</th><thclassName="pb-2pr-4">Issue</th>
<thclassName="pb-2pr-4">Priority</th><thclassName="pb-2pr-4">Status</th><thclassName="pb-2">Date</th>
</tr></thead>
<tbody>
{allMaintenance.map((m:any)=>(
<trkey={m.id}className="border-bborder-gray-50hover:bg-gray-50">
<tdclassName="py-2pr-4font-mediumtext-gray-800">{m.vehicle?.plateNumber||'N/A'}</td>
<tdclassName="py-2pr-4text-gray-600truncatemax-w-[160px]">{m.issueDescription?.slice(0,50)||'N/A'}</td>
<tdclassName="py-2pr-4"><spanclassName={`px-2py-0.5roundedtext-xs${m.priority==='Critical'?'bg-red-100text-red-700':m.priority==='High'?'bg-orange-100text-orange-700':'bg-gray-100text-gray-600'}`}>{m.priority||'Normal'}</span></td>
<tdclassName="py-2pr-4"><spanclassName={`px-2py-0.5roundedtext-xs${m.status==='Completed'?'bg-green-100text-green-700':'bg-yellow-100text-yellow-700'}`}>{m.status}</span></td>
<tdclassName="py-2text-xstext-gray-400">{m.createdAt?newDate(m.createdAt).toLocaleDateString():'N/A'}</td>
</tr>
))}
{allMaintenance.length===0&&<tr><tdcolSpan={5}className="py-8text-centertext-gray-400">Nomaintenancerecordsfound</td></tr>}
</tbody>
</table>
</div>
</div>
</div>
)}
</div>
)
}


