constAPI_BASE_URL=
process.env.NEXT_PUBLIC_API_URL||'https://exact-journals-interfaces-sure.trycloudflare.com/api/v1'

//GetauthtokenfromlocalStorageorsessionStorage
constgetAuthToken=()=>{
if(typeofwindow!=='undefined'){
return(
localStorage.getItem('accessToken')||
sessionStorage.getItem('accessToken')||
localStorage.getItem('access_token')||
sessionStorage.getItem('access_token')||
null
)
}
returnnull
}

constgetRefreshToken=()=>{
if(typeofwindow!=='undefined'){
returnlocalStorage.getItem('refreshToken')||sessionStorage.getItem('refreshToken')||null
}
returnnull
}

//Createheaderswithauthtoken
constcreateHeaders=()=>{
consttoken=getAuthToken()
return{
'Content-Type':'application/json',
...(token&&{Authorization:`Bearer${token}`})
}
}

//Deduplicatedrefreshpromise
let_refreshPromise:Promise<boolean>|null=null

asyncfunctionrefreshAccessToken():Promise<boolean>{
if(_refreshPromise)return_refreshPromise
_refreshPromise=(async()=>{
constrefreshToken=getRefreshToken()
if(!refreshToken)returnfalse
try{
constres=awaitfetch(`${API_BASE_URL}/auth/refresh`,{
method:'POST',
headers:{'Content-Type':'application/json'},
body:JSON.stringify({refresh_token:refreshToken}),
})
if(!res.ok)returnfalse
constdata=awaitres.json()
conststorage=localStorage.getItem('refreshToken')?localStorage:sessionStorage
storage.setItem('accessToken',data.access_token)
if(data.refresh_token)storage.setItem('refreshToken',data.refresh_token)
returntrue
}catch{
returnfalse
}finally{
_refreshPromise=null
}
})()
return_refreshPromise
}

functionclearSession(){
;['accessToken','access_token','refreshToken','user'].forEach((k)=>{
localStorage.removeItem(k)
sessionStorage.removeItem(k)
})
}

//HandleAPIresponseswithauto-refresh
asyncfunctionhandleResponse(response:Response,retry:()=>Promise<Response>):Promise<any>{
if(response.status===401){
constrefreshed=awaitrefreshAccessToken()
if(refreshed){
constretried=awaitretry()
if(!retried.ok){
consterror=awaitretried.json().catch(()=>({message:'Networkerror'}))
thrownewError(error.message||'APIrequestfailed')
}
returnretried.json()
}
clearSession()
if(typeofwindow!=='undefined')window.location.href='/login'
thrownewError('Sessionexpired.Pleaseloginagain.')
}
if(!response.ok){
consterror=awaitresponse.json().catch(()=>({message:'Networkerror'}))
thrownewError(error.message||'APIrequestfailed')
}
returnresponse.json()
}

//Conveniencewrapper
asyncfunctionapiFetch(url:string,options:RequestInit={}):Promise<any>{
constheaders={...createHeaders(),...(options.headersasRecord<string,string>)}
constresponse=awaitfetch(url,{...options,headers})
returnhandleResponse(response,()=>{
constnewHeaders={...createHeaders(),...(options.headersasRecord<string,string>)}
returnfetch(url,{...options,headers:newHeaders})
})
}

//AuthAPI
exportconstauthApi={
login:async(email:string,password:string)=>{
constresponse=awaitfetch(`${API_BASE_URL}/auth/login`,{
method:'POST',
headers:{'Content-Type':'application/json'},
body:JSON.stringify({email,password})
})
if(!response.ok){
consterror=awaitresponse.json().catch(()=>({message:'Loginfailed'}))
thrownewError(error.message||'Loginfailed')
}
returnresponse.json()
},

getCurrentUser:async()=>apiFetch(`${API_BASE_URL}/users/me`)
}

//TripAPI-DeploymentOfficemanagesapprovedtrips
exportconsttripApi={
getApprovedTrips:async()=>{
consttrips=awaitapiFetch(`${API_BASE_URL}/trips`)
returnArray.isArray(trips)
?trips.filter((trip:any)=>trip.state==='APPROVED_FOR_ALLOCATION')
:[]
},

getAllTrips:async()=>apiFetch(`${API_BASE_URL}/trips`),

assignVehicleAndDriver:async(tripId:string,vehicleId:string,driverId:string,estimatedFuelCost=0,estimatedDistance=0)=>
apiFetch(`${API_BASE_URL}/trips/${tripId}/allocate`,{
method:'POST',
body:JSON.stringify({vehicleId,driverId,estimatedFuelCost,estimatedDistance})
}),

updateTripStatus:async(tripId:string,status:string,notes?:string)=>{
constendpoint=status==='IN_PROGRESS'?'start':'complete'
returnapiFetch(`${API_BASE_URL}/trips/${tripId}/${endpoint}`,{
method:'POST',
body:JSON.stringify({status,notes})
})
}
}

//VehicleAPI
exportconstvehicleApi={
getAllVehicles:async()=>apiFetch(`${API_BASE_URL}/vehicles`),
getAvailableVehicles:async()=>apiFetch(`${API_BASE_URL}/vehicles/available`),
createVehicle:async(vehicleData:any)=>
apiFetch(`${API_BASE_URL}/vehicles`,{method:'POST',body:JSON.stringify(vehicleData)}),
updateVehicle:async(vehicleId:string,vehicleData:any)=>
apiFetch(`${API_BASE_URL}/vehicles/${vehicleId}`,{method:'PATCH',body:JSON.stringify(vehicleData)}),
deleteVehicle:async(vehicleId:string)=>
apiFetch(`${API_BASE_URL}/vehicles/${vehicleId}`,{method:'DELETE'}),
getVehicleStats:async()=>apiFetch(`${API_BASE_URL}/vehicles/statistics`)
}

//DriverAPI
exportconstdriverApi={
getAllDrivers:async()=>apiFetch(`${API_BASE_URL}/drivers`),
getAvailableDrivers:async()=>apiFetch(`${API_BASE_URL}/drivers/available`),
createDriver:async(driverData:any)=>
apiFetch(`${API_BASE_URL}/drivers`,{method:'POST',body:JSON.stringify(driverData)}),
updateDriver:async(driverId:string,driverData:any)=>
apiFetch(`${API_BASE_URL}/drivers/${driverId}`,{method:'PATCH',body:JSON.stringify(driverData)}),
deleteDriver:async(driverId:string)=>
apiFetch(`${API_BASE_URL}/drivers/${driverId}`,{method:'DELETE'})
}

//MaintenanceAPI
exportconstmaintenanceApi={
getAllMaintenanceRequests:async()=>apiFetch(`${API_BASE_URL}/maintenance`),
createMaintenanceRequest:async(maintenanceData:any)=>
apiFetch(`${API_BASE_URL}/maintenance`,{method:'POST',body:JSON.stringify(maintenanceData)}),
updateMaintenanceRequest:async(requestId:string,data:any)=>
apiFetch(`${API_BASE_URL}/maintenance/${requestId}/inspect`,{method:'POST',body:JSON.stringify(data)})
}

//Statistics
exportconststatsApi={
getDeploymentStats:async()=>{
const[vehicles,trips,maintenance]=awaitPromise.all([
vehicleApi.getAllVehicles().catch(()=>[]),
tripApi.getAllTrips().catch(()=>[]),
maintenanceApi.getAllMaintenanceRequests().catch(()=>[]),
])
constvehiclesArr=Array.isArray(vehicles)?vehicles:[]
consttripsArr=Array.isArray(trips)?trips:[]
constmaintenanceArr=Array.isArray(maintenance)?maintenance:[]
return{
totalFleet:vehiclesArr.length,
available:vehiclesArr.filter((v:any)=>v.status==='Active').length,
inUse:tripsArr.filter((t:any)=>t.state==='IN_PROGRESS').length,
maintenance:maintenanceArr.filter((m:any)=>m.status!=='Completed').length,
activeTrips:tripsArr.filter((t:any)=>t.state==='IN_PROGRESS').length,
pendingAllocation:tripsArr.filter((t:any)=>t.state==='APPROVED_FOR_ALLOCATION').length,
}
},
getFleetUtilization:async()=>apiFetch(`${API_BASE_URL}/vehicles/statistics`)
}

//NotificationsAPI
exportconstnotificationApi={
getNotifications:async()=>apiFetch(`${API_BASE_URL}/notifications`),
markAsRead:async(notificationId:string)=>
apiFetch(`${API_BASE_URL}/notifications/${notificationId}/read`,{method:'PATCH'})
}

//ReportsAPI
exportconstreportApi={
generateDeploymentReport:async(filters:any)=>
apiFetch(`${API_BASE_URL}/reports/deployment`,{method:'POST',body:JSON.stringify(filters)}),
generateVehicleUtilizationReport:async(filters:any)=>
apiFetch(`${API_BASE_URL}/reports/vehicle-utilization`,{method:'POST',body:JSON.stringify(filters)}),
generateMaintenanceReport:async(filters:any)=>
apiFetch(`${API_BASE_URL}/reports/maintenance`,{method:'POST',body:JSON.stringify(filters)})
}

